apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: netwin-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: netwin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: 1.0.7-r1
    helm.sh/chart: netwin-0.1.0
  name: netwin-frontend
  namespace: netwin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/app: netwin-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: netwin-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: netwin
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: frontend
        app.kubernetes.io/version: 1.0.7-r1
        helm.sh/chart: netwin-0.1.0
    spec:
      containers:
      - args:
        - netwin_frontend
        env:
        - name: IAM_URL
          value: https://iam-dev-vtal.10.51.195.98.nip.io
        envFrom:
        - secretRef:
            name: netwin-credentials
        image: ghcr.io/alticelabsprojects/inventory-vtal:1.0.7-r1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 9500
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: netwin-frontend
        ports:
        - containerPort: 9500
          name: http
          protocol: TCP
        - containerPort: 40002
          name: securitycache
          protocol: TCP
        - containerPort: 9021
          name: debug
          protocol: TCP
        - containerPort: 8886
          name: prom-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 9500
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /opt/alticelabs/automation/netwin/inventory/hosts
          name: deploy-conf
          subPath: hosts
        - mountPath: /tmp/log
          name: varlog
        - mountPath: /opt/alticelabs/automation/netwin/iamcerts/ca.crt
          name: altice-ca
          subPath: ca.crt
      imagePullSecrets:
      - name: acr-secret
      - name: ghcr-secret
      initContainers:
      - command:
        - sh
        - -c
        - cp -rp /var/log/* /tmp/log || true
        image: ghcr.io/alticelabsprojects/inventory-vtal:1.0.7-r1
        imagePullPolicy: Always
        name: init-log-dir
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp/log
          name: varlog
      securityContext:
        runAsGroup: 1009
        runAsUser: 992
      serviceAccountName: sa-nossis
      volumes:
      - configMap:
          defaultMode: 420
          name: netwin-deploy-conf
        name: deploy-conf
      - emptyDir: {}
        name: varlog
      - name: altice-ca
        secret:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          secretName: netwin-web-certificate
