apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: netwin-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: netwin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: 1.0.6-r2
    helm.sh/chart: netwin-0.1.0
  name: netwin-backend
  namespace: netwin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/app: netwin-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: netwin-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: netwin
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: backend
        app.kubernetes.io/version: 1.0.6-r2
        helm.sh/chart: netwin-0.1.0
    spec:
      securityContext:
        runAsGroup: 1009
        runAsUser: 992
      serviceAccountName: sa-nossis
      imagePullSecrets:
        - name: acr-secret
        - name: ghcr-secret
      initContainers:
        - name: init-log-dir
          image: ghcr.io/alticelabsprojects/inventory-vtal:1.0.6-r2
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - cp -rp /var/log/* /tmp/log || true
          resources:
            limits:
              cpu: 75m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /tmp/log
              name: varlog
      containers:
        - name: netwin-backend
          image: ghcr.io/alticelabsprojects/inventory-vtal:1.0.6-r2
          imagePullPolicy: Always
          args:
            - netwin_backend
          env:
            - name: JBOSS_HTTPS_PORT
              value: "443"
          envFrom:
            - secretRef:
                name: netwin-credentials
          ports:
            - containerPort: 9015
              name: http
              protocol: TCP
            - containerPort: 9016
              name: http-debug
              protocol: TCP
            - containerPort: 8891
              name: prom-metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health/live
              port: 9015
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health/ready
              port: 9015
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /opt/alticelabs/automation/netwin/inventory/hosts
              name: deploy-conf
              subPath: hosts
            - mountPath: /var/log
              name: varlog
            - mountPath: /opt/alticelabs/automation/netwin/certs/ca.crt
              name: altice-ca
              subPath: ca.crt
      volumes:
        - name: deploy-conf
          configMap:
            defaultMode: 420
            name: netwin-deploy-conf
        - name: varlog
          emptyDir: {}
        - name: altice-ca
          secret:
            defaultMode: 420
            secretName: netwin-web-certificate
            items:
              - key: ca.crt
                path: ca.crt
