apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.51.195.98"],"port":443,"protocol":"HTTPS","serviceName":"netwin:netwin-loadbalancer","ingressName":"netwin:netwin-ingress","hostname":"netwin-dev-vtal.10.51.195.98.nip.io","path":"/","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/app":"netwin-loadbalancer","app.kubernetes.io/component":"loadbalancer","app.kubernetes.io/instance":"netwin","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"loadbalancer","app.kubernetes.io/version":"1.0.5-r3","helm.sh/chart":"netwin-0.1.0"},"name":"netwin-loadbalancer","namespace":"netwin"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/app":"netwin-loadbalancer"}},"template":{"metadata":{"labels":{"app.kubernetes.io/app":"netwin-loadbalancer","app.kubernetes.io/component":"loadbalancer","app.kubernetes.io/instance":"netwin","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"loadbalancer","app.kubernetes.io/version":"1.0.5-r3","helm.sh/chart":"netwin-0.1.0"}},"spec":{"containers":[{"args":["netwin_lb_fe"],"envFrom":[{"secretRef":{"name":"netwin-credentials"}}],"image":"acrdevopsfbdev2demo.azurecr.io/netwin/inventory-vtal-lb:1.0.5-r3","imagePullPolicy":"Always","name":"netwin-loadbalancer","ports":[{"containerPort":8443,"name":"https"},{"containerPort":8080,"name":"http"},{"containerPort":9113,"name":"prom-metrics"}],"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"75m","memory":"128Mi"}},"securityContext":{"runAsNonRoot":true},"volumeMounts":[{"mountPath":"/opt/alticelabs/automation/netwin/inventory/hosts","name":"deploy-conf","subPath":"hosts"},{"mountPath":"/opt/alticelabs/automation/netwin/certs/tls.crt","name":"nginx-cert","subPath":"tls.crt"},{"mountPath":"/opt/alticelabs/automation/netwin/certs/tls.key","name":"nginx-cert","subPath":"tls.key"}]}],"securityContext":{"runAsGroup":998,"runAsUser":999},"serviceAccountName":"default","volumes":[{"configMap":{"name":"netwin-deploy-conf"},"name":"deploy-conf"},{"name":"nginx-cert","secret":{"items":[{"key":"tls.crt","path":"tls.crt"},{"key":"tls.key","path":"tls.key"}],"secretName":"loadbalancer-crt"}}]}}}}
  creationTimestamp: "2025-12-22T15:12:48Z"
  generation: 34
  labels:
    app.kubernetes.io/app: netwin-loadbalancer
    app.kubernetes.io/component: loadbalancer
    app.kubernetes.io/instance: netwin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loadbalancer
    app.kubernetes.io/version: 1.0.5-r3
    helm.sh/chart: netwin-0.1.0
  name: netwin-loadbalancer
  namespace: netwin
  resourceVersion: "204541947"
  uid: 2f57a438-a0c0-4035-b32e-246818e10590
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/app: netwin-loadbalancer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-12T22:29:31-03:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/app: netwin-loadbalancer
        app.kubernetes.io/component: loadbalancer
        app.kubernetes.io/instance: netwin
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: loadbalancer
        app.kubernetes.io/version: 1.0.5-r3
        helm.sh/chart: netwin-0.1.0
    spec:
      containers:
      - args:
        - netwin_lb_fe
        envFrom:
        - secretRef:
            name: netwin-credentials
        image: ghcr.io/alticelabsprojects/inventory-vtal-lb:1.0.6-r2
        imagePullPolicy: Always
        name: netwin-loadbalancer
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9113
          name: prom-metrics
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 75m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/alticelabs/automation/netwin/inventory/hosts
          name: deploy-conf
          subPath: hosts
        - mountPath: /opt/alticelabs/automation/netwin/certs/tls.crt
          name: nginx-cert
          subPath: tls.crt
        - mountPath: /opt/alticelabs/automation/netwin/certs/tls.key
          name: nginx-cert
          subPath: tls.key
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-secret
      - name: ghcr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 998
        runAsUser: 999
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: netwin-deploy-conf
        name: deploy-conf
      - name: nginx-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: netwin-web-certificate
status:
  conditions:
  - lastTransitionTime: "2026-03-25T03:52:40Z"
    lastUpdateTime: "2026-03-25T03:52:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-22T15:12:49Z"
    lastUpdateTime: "2026-03-25T03:52:40Z"
    message: ReplicaSet "netwin-loadbalancer-754b699447" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 34
